export const METHOD_TYPE = {
    get: "get",
    post: "post",
    put: "put",
    delete: "delete",
};

export const API_ENDPOINTS = {
    trendingLatestStocks: 'stocks/trending',
    trendingLatestNews: 'news/trending',
    getMostFrruitGpt: 'users/getMostOnFruitGPT?limit=',
    getUserWatchList: 'watchlist/fetchWatchList',
    getTickersById: 'watchlist/fetchWatchListTickerByWatchlist',
    frruitGptSuggestion: 'stocks/getSuggestionPrompts',
    fetchTrendingEvents: 'eventCategories/fetchtrendingEvents',
    signupOtp: 'users/sendSignUpOtp',
    verifyOtp: 'users/verifyOtp',
    signup: 'users/signup',
    getPlans: 'plans',
    placeOrder: 'order/placeOrder',
    login: 'users/sendotp',
    verifyLogin: 'users/verifyLoginMobileNo',
    getUserDetails: 'users/userDetails',
    updateProfile: 'users/updateProfile',
    initiateOrder: 'order/initiateOrder',
    placeOrder: 'order/placeOrder',
    getAllTopics: 'topic/getTopics',
    addTopics: 'users/addUserTopics',
    searchTopics: 'topic/searchTopics',
    userTopics: 'topic/getTopicsByUserId',
    updateTopics: 'users/updateTopics',
    getPromptList: 'prompts/getPrompts',
    addPrompt: 'prompts/addPrompts',
    getPromptHistory: 'prompts/getPromptHistory?prompt_id=',
    searchPrompt: 'prompts/searchPrompts?prompt=',
    triggerChatGpt: 'prompts/triggerChat',
    stockSearchByKeyword: 'stocks/getStockBySearch?keyword=',
    getUserActivePlan: 'users/getUserActivePlan',
    stockSectors: 'stocks/sp500',
    getAvailableCredits: 'users/getAvaliableCredit',
    addWatchList: 'watchlist/addWatchList',
    editWatchList: 'watchlist/editWatchList?watchListId=',
    deleteWatchList: 'watchlist/deleteWatchList?watchListId=',
    addTickerToWatchList: 'watchlist/addTickertoWatchList',
    removeTickerFromWatchList: 'watchlist/removeTickerFromWatchList?watchListTickerId=',
    stockIndexes: 'stocks/indexes',
    getCompanyDetail: 'stocks/getCompanyDetail',
    getStockStatistics: 'stocks/getStockStatistics',
    getNewsReference: 'news/reference',
    getGraphDetail: 'stocks/getGraphDetail',
    getStockBySearch: 'stocks/getStockBySearch',
    getInvestorStories: 'users/getInvestorStories',
    triggerGPTGraph: 'prompts/triggerGraph',
    triggerContentPrompt: 'contentPrompt/triggerContentPrompt',
    get_uploadUrl: '/contentPrompt/getSignedUrl',
    triggerDocumentChat: 'contentPrompt/triggerDocumentChat',
    addDocument: 'contentPrompt/addDocument',
    getContentPromptList: 'contentPrompt/getContentPromptHistory?type=',
    getContentPromptHistory: 'contentPrompt/getContentPromptHistoryByContentPromptId?content_prompt_id=',
    searchContentPrompt: 'contentPrompt/searchContentPrompts',
    getPromptsLibrary: 'promptlibrary/getPrompts',
    deleteContentPrompt: 'contentPrompt/deleteContentPrompt?promptId=',
    deletePrompt: 'prompts/deletePrompt?promptId=',
    deductEventCredits: 'users/deductEventCredits',
    triggerLinkGraph: 'contentPrompt/triggerLinkGraph',
    triggerAttachmentGraph: 'contentPrompt/triggerAttachmentGraph',
    fetchAllNews: 'news/fetchAllNews',
    getOrderHistory: 'order/getUserOrders',
    searchSuggestedQuestionPrompts: 'prompts/searchSuggestedQuestionPrompts?prompt=',
    fetchTrendingStocksFromAI: 'stocks/fetchTrendingStocksFromAI',
    getStockOverview : 'stocks/getStockOverview',
    getFinancialsPeers : 'stocks/getFinancialsPeers',
    getFinancialsShareHolding : 'stocks/getFinancialsShareHolding',
    getStockRevenue : 'stocks/getStockRevenue',
    resendOtp: 'users/resendOtp',
    userFeedback: 'users/userFeedback',
}