import React from 'react'

function TermsAndCondition() {
    return (
        <div className='privacypolicy-css'>
            <div className=''>
                <h3 className='main-heading'>Frruit’s TERMS OF SERVICE</h3>
                <p className='updated-date'>Last updated: June 4th, 2024.</p>
                {/* <p className='text-subheading1'>
                    Welcome to the Terms of Service (these “Terms”) for Perplexity AI, Inc.’s (“Company”, “we” or “us”) websites, www.perplexity.ai and https://labs.perplexity.ai (the “Websites”), artificial-intelligence powered search engine (the “Perplexity Engine”), related mobile application (the “App”), and any content, tools, features and functionality offered on or through our Website, the Perplexity Engine and the App (collectively, the “Services”). These Terms do not govern use of the Company’s APIs (which are governed by the Perplexity API Terms of Service located here: https://www.perplexity.ai/hub/legal/perplexity-api-terms-of-service) or Perplexity Pro for Enterprise (which is governed by the Perplexity Pro for Enterprise Terms located here: (https://www.perplexity.ai/hub/legal/enterprise-terms-of-service).
                </p>
                <p className='text-subheading1'>
                    These Terms govern your access to and use of the Services.  Please read these Terms carefully, as they include important information about your legal rights. By accessing and/or using the Services, you are agreeing to these Terms. If you do not understand or agree to these Terms, please do not use the Services.
                </p>
                <p className='text-subheading1'>
                    For purposes of these Terms, “you” and “your” means you as the user of the Services. If you use the Services on behalf of a company or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity’s behalf.
                </p>
                <p className='text-subheading1'>
                    SECTION 9 CONTAINS AN ARBITRATION CLAUSE AND CLASS ACTION WAIVER. BY AGREEING TO THESE TERMS, YOU AGREE (A) TO RESOLVE ALL DISPUTES (WITH LIMITED EXCEPTION) RELATED TO THE COMPANY’S SERVICES AND/OR PRODUCTS THROUGH BINDING INDIVIDUAL ARBITRATION, WHICH MEANS THAT YOU WAIVE ANY RIGHT TO HAVE THOSE DISPUTES DECIDED BY A JUDGE OR JURY, AND (B) TO WAIVE YOUR RIGHT TO PARTICIPATE IN CLASS ACTIONS, CLASS ARBITRATIONS, OR REPRESENTATIVE ACTIONS, AS SET FORTH BELOW. YOU HAVE THE RIGHT TO OPT-OUT OF THE ARBITRATION CLAUSE AND THE CLASS ACTION WAIVER AS EXPLAINED IN SECTION 9.
                </p>
                <h2 className='text-heading'>1. The Services</h2>
                <div className='box1'>
                    <p className='subtext'>1.1 The Services</p>
                    <p className='text-subheading3'>
                        <span className='headpoint'>a.</span> As a part of the Services, you can input, upload and submit information and other materials (“Input”) into the Perplexity Engine, and the Perplexity Engine will use artificial intelligence tools and functionalities to generate responses based on your Input (“Output”). Your use of the Perplexity Engine, including any Outputs, may also be subject to license and use restrictions set forth in a third-party LLM license, if applicable. Any Input will be deemed “Your Content” under these Terms.
                    </p>
                    <p className='text-subheading3'>
                        <span className='headpoint'>b.</span> You may not direct the Services to generate any Output in violation of any applicable intellectual property right, contractual restriction or other law. By submitting any Input through the Services, you represent that you have obtained all rights, licenses, consents, permissions, power and/or authority necessary to submit and use (and allow us to use) such Input in connection with the Services. You represent and warrant that your submission of Input in connection with your use of the Services, including to generate Output, will not breach any law or any third party’s terms and conditions associated with such Input. You may not (i) publish any Output generated by the Services without clearly citing the Services, or (ii) misrepresent the source of any Output or the fact that it was generated by artificial intelligence.
                    </p>
                    <p className='subtext'>1.2 Eligibility</p>
                    <p className='text-subheading3'>
                        You must be 13 years of age or older to use the Services. Minors under the age of majority in their jurisdiction but that are at least 13 years of age are only permitted to use the Services if the minor’s parent or guardian accepts these Terms on the minor’s behalf prior to use of the Services. Children under the age of 13 are not permitted to use the Services. By using the Services, you represent and warrant that you meet these requirements.
                    </p>
                </div>
                <h2 className='text-heading'>2. User Accounts, SUBSCRIPTIONS and free trials</h2>
                <div className='box1'>
                    <p className='subtext' style={{ marginTop: 10 }}>2.1 Creating and Safeguarding your Account</p>
                    <p className='text-subheading3'>
                        To use certain of the Services, you need to create an account or link another account, such as your Apple or Google account (“Account”). You agree to provide us with accurate, complete and updated information for your Account. You can access, edit and update your Account through the settings page of your Account profile. You are solely responsible for any activity on your Account and for maintaining the confidentiality and security of your password. We are not liable for any acts or omissions by you in connection with your Account. You must immediately notify us at support@perplexity.ai if you know or have any reason to suspect that your Account or password have been stolen, misappropriated or otherwise compromised, or in case of any actual or suspected unauthorized use of your Account. You agree not to create an Account if we have previously removed your Account, or we previously banned you from any of our Services, unless we provide written consent otherwise.
                    </p>
                    <p className='subtext'>2.2 Paid Services</p>
                    <p className='text-subheading3'>
                        To use certain of the Services, you need to create an account or link another account, such as your Apple or Google account (“Account”). You agree to provide us with accurate, complete and updated information for your Account. You can access, edit and update your Account through the settings page of your Account profile. You are solely responsible for any activity on your Account and for maintaining the confidentiality and security of your password. We are not liable for any acts or omissions by you in connection with your Account. You must immediately notify us at support@perplexity.ai if you know or have any reason to suspect that your Account or password have been stolen, misappropriated or otherwise compromised, or in case of any actual or suspected unauthorized use of your Account. You agree not to create an Account if we have previously removed your Account, or we previously banned you from any of our Services, unless we provide written consent otherwise.
                    </p>
                    <p className='subtext'>2.3 Subscription Renewals and Cancellations</p>
                    <p className='text-subheading3'>
                        Subscription Renewals and Cancellations. You agree that if you purchase a subscription, your subscription will automatically renew at the subscription period frequency referenced on your subscription page (or if not designated, then monthly) and at the then-current rates, and your payment method will automatically be charged at the start of each new subscription period for the fees and taxes applicable to that period.  To avoid future subscription charges, you must cancel your subscription before the subscription period renewal date through the settings page of your Account profile or by emailing support@perplexity.ai.
                    </p>
                    <p className='subtext'>2.4 No Subscription Refunds.</p>
                    <p className='text-subheading3'>
                        Except as expressly set forth in these Terms, payments for any subscriptions to the Services are nonrefundable and there are no credits for partially used periods. Following any cancellation by you, however, you will continue to have access to the paid Services through the end of the subscription period for which payment has already been made.
                    </p>
                </div>
                <h2 className='text-heading'>2. ORDERS FOR PRODUCTS AND/OR SERVICES </h2>
                <div className='box1'>
                    <p className='subtext' style={{ marginTop: 10 }}>3.1 Payment</p>
                    <p className='text-subheading3'>
                        The Services may permit you to purchase certain other products or services, such as merchandise (“Offerings”).  You acknowledge and agree that all information you provide with regards to a purchase of Offerings, including, without limitation, credit card, PayPal, or other payment information, is accurate, current and complete. You represent and warrant that you have the legal right to use the payment method you provide to us or our payment processor, including, without limitation, any credit card you provide when completing a transaction. We reserve the right, with or without prior notice and in our sole and complete discretion, to (a) discontinue, modify, or limit the available quantity of, any Offerings, and (b) refuse to allow any user to purchase any Offering or deliver such Offerings to a user or a user designated address. When you purchase Offerings, you (i) agree to pay the price for such Offerings as set forth in the applicable Service, and all shipping and handling charges and all applicable taxes in connection with your purchase (the “Full Purchase Amount”), and (ii) authorize us to charge your credit card or other payment method for the Full Purchase Amount. Unless otherwise noted, all currency references are in U.S. Dollars. All fees and charges are payable in accordance with payment terms in effect at the time the fee or the charge becomes payable. Payment can be made by credit card, debit card, or through PayPal or other means that we may make available. Orders will not be processed until payment has been received in full, and any holds on your account by PayPal or any other payment processor are solely your responsibility.
                    </p>
                    <p className='subtext'>3.2 Promotional Codes</p>
                    <p className='text-subheading3'>
                        We may offer certain promotional codes, referral codes, discount codes, coupon codes or similar offers (“Promotional Codes”) that may be redeemed for discounts on benefits related to the Services or future Offerings, subject to any additional terms that the Company establishes. You agree that Promotional Codes: (a) must be used in a lawful manner; (b) must be used for the intended audience and purpose; (c) may not be duplicated, sold or transferred in any manner, or made available by you to the general public (whether posted to a public forum, coupon collecting service, or otherwise), unless expressly permitted by the Company; (d) may be disabled or have additional conditions applied to them by the Company at any time for any reason without liability to the Company; (e) may only be used pursuant to the specific terms that the Company establishes for such Promotional Code; (f) are not valid for cash or other credits or points; and (g) may expire prior to your use.
                    </p>
                </div> */}
            </div>
        </div>
    )
}

export default TermsAndCondition